### ISSUE TITLE
LuaSTG Sub updates gltf 2.0 renderer, fixed some bugs

### ISSUE THREAD

**Issue by Demonese** [KaleiAlma/LuaSTG-Evo#5]
I'm sorry, there were some issues with the code I wrote a year ago. It has now been fixed.

**Comment by KaleiAlma** [comment]
The rendering code is somewhat different between Sub and Evo due to the API difference, so I believe the bug may have been fixed upon porting to OpenGL. Will reopen if I find out that I somehow kept this bug in despite that.

PS: I would like to discuss LuaSTG engine development. I have both sent you a message on Discord and e-mailed you at your Outlook address. I would prefer Discord, but either means is acceptable.

**Comment by Demonese** [comment]
> PS：我想讨论一下LuaSTG引擎的开发。我已经在 Discord 上向您发送了一条消息，并在您的 Outlook 地址向您发送电子邮件。我更喜欢 Discord，但任何一种方式都是可以接受的。

My Microsoft account has been hacked, I registered a new email git@chuikingshek.com.

我的微软账号被黑了。现在注册了新的电子邮箱 git@chuikingshek.com。

**Comment by KaleiAlma** [comment]
Alright.
